<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddFoodBrandNewVersion</name>
   <tag></tag>
   <elementGuidId>388633fe-d571-4afb-89bb-96064679fd00</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blanja-default-form data-spesifikasi-false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-produk</name>
      <type>Main</type>
      <value>food-brand</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mandatory</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Food BrandAurellaBERASKITABanua CokelatBatagor RiriBelvitaBeras CililinCadburyCap Ayam Mami's Mente GorengChaChaCipagantiCorn FlakesDIAMOND SWISSDelfiEasymixGarudaFoodGood DayHersheyJATISARIKapal ApiKellogg'sKinderKissesKitkatKoko KrunchKonimexLaysLuve CakeNarayaNature Rice IndonesiaNo BrandNutellaNutter ButterNyonya_SetroongOreoOvomaltinePop tartsPrima RasaPringlesPutriMaritzaQuackerReboReese'sRitzSOYJOYSerambi BotaniSilverQueenSkittlesSnack OriginalSnickersSpesial BUNONISribogaStarbursStarburstThe KrippsTiara Ujung PandangToarcoTobleroneTwixWonkam&amp;m'stictac</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result-spesifikasi&quot;)/div[@class=&quot;form-group-row&quot;]/div[@class=&quot;data-produk&quot;]/select[@class=&quot;blanja-default-form data-spesifikasi-false&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='result-spesifikasi']/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Food Brand'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spesifikasi'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Varian'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/select</value>
   </webElementXpaths>
</WebElementEntity>
