<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hrefPDPOnOrderConfirm</name>
   <tag></tag>
   <elementGuidId>7cda5446-c257-42f5-9142-3279f9a786c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;productDetailDiv&quot;)/ul[@class=&quot;store-order-list&quot;]/li[@class=&quot;p20&quot;]/ul[@class=&quot;store-product-list&quot;]/li[1]/div[@class=&quot;product-container clearfix&quot;]/div[@class=&quot;left&quot;]/div[@class=&quot;product-detail ml10&quot;]/p[1]/a[@class=&quot;fColor-black&quot;][count(. | //a[@href = 'https://www.bljstaging.com/katalog/p/fas/t-shirt-o-neck-unisex-9-pilihan-warna--13871460' and @class = 'fColor-black']) = count(//a[@href = 'https://www.bljstaging.com/katalog/p/fas/t-shirt-o-neck-unisex-9-pilihan-warna--13871460' and @class = 'fColor-black'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productDetailDiv']/ul/li/ul/li/div/div/div[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bljstaging.com/katalog/p/fas/t-shirt-o-neck-unisex-9-pilihan-warna--13871460</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fColor-black</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T-Shirt O-Neck Unisex (9 Pilihan Warna)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productDetailDiv&quot;)/ul[@class=&quot;store-order-list&quot;]/li[@class=&quot;p20&quot;]/ul[@class=&quot;store-product-list&quot;]/li[1]/div[@class=&quot;product-container clearfix&quot;]/div[@class=&quot;left&quot;]/div[@class=&quot;product-detail ml10&quot;]/p[1]/a[@class=&quot;fColor-black&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='productDetailDiv']/ul/li/ul/li/div/div/div[2]/p/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'T-Shirt O-Neck Unisex (9 Pilihan Warna)')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon lengkapi lokasi peta pada alamat Anda untuk menggunakan kurir ini.'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STEPHANO'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warna : Hijau Army'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>(//a[contains(@href, 'https://www.bljstaging.com/katalog/p/fas/t-shirt-o-neck-unisex-9-pilihan-warna--13871460')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/p/a</value>
   </webElementXpaths>
</WebElementEntity>
