<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LastOrderNumberBlanjaanSaya</name>
   <tag></tag>
   <elementGuidId>0b763baa-cb90-4068-b61c-1c4c055bf45b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tradesTable&quot;]/div[2]/div/table/thead/tr/th/div[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-num</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tradesTable&quot;]/div[2]/div/table/thead/tr/th/div[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
