<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyPembayaran</name>
   <tag></tag>
   <elementGuidId>fcb546fb-42d4-40fc-850e-839de97da11a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tradesTable&quot;]/div[2]/div/table/thead/tr/th/div[1]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tradesTable&quot;]/div[2]/div/table/thead/tr/th/div[1]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
