<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelLihatDetil</name>
   <tag></tag>
   <elementGuidId>84e20a98-717b-4ac9-8ecf-84253806c403</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-period</name>
      <type>Main</type>
      <value>25 March 2019 - 30 March 2019</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-threshold</name>
      <type>Main</type>
      <value>5.000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxcover</name>
      <type>Main</type>
      <value>30.000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activity</name>
      <type>Main</type>
      <value>2309</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promoSellerActivityInfo fColor-red</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detil</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;bgColor-white&quot;]/div[@class=&quot;wrapper-pdp pt30 pb30 clearfix&quot;]/section[@class=&quot;main-content fLeft&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;product-info fRight&quot;]/div[@class=&quot;product-detail mt10 pb15 width-full&quot;]/div[@class=&quot;product-shipment clearfix pt5&quot;]/div[@class=&quot;product-line multiple-freeshipping&quot;]/div[@class=&quot;promotion-seller-activity-content&quot;]/div[@class=&quot;promotion-seller-activity-info&quot;]/div[1]/span[@class=&quot;promoSellerActivityInfo fColor-red&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Shipping Seller'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambahkan ke Troli'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blanja sekarang'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/div/span[3]</value>
   </webElementXpaths>
</WebElementEntity>
