<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblFinpayPembayaranTry</name>
   <tag></tag>
   <elementGuidId>3387bb63-0cb3-4d6c-8cea-85992a062d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat selengkapnya'])[9]/following::span[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'rdi-box' and @value = 'finpay_195_atm' and @name = 'pay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdi-box</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;inner-wrapper content clear blj-wrapper&quot;]/div[@class=&quot;choosepay-panel choosepay&quot;]/div[@class=&quot;checkout-sec no-padding&quot;]/div[@class=&quot;input-content&quot;]/ul[@class=&quot;choosepay-method&quot;]/li[8]/label[1]/span[@class=&quot;blanja-radio-label&quot;]/span[@class=&quot;choosepay-method-img&quot;]/span[@class=&quot;sprite-payment sprite-finpay_195_atm&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>finpay_195_atm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pay</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat selengkapnya'])[9]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//li[8]/label/span/span[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
