<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddDikirimKe</name>
   <tag></tag>
   <elementGuidId>40104adb-29de-4ac8-9a6c-cd0a9d0f6ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='state']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'state' and (text() = '
				                    	Please select state				                    BaliBantenBengkuluDaerah Istimewa YogyakartaDKI JakartaGorontaloJawa BaratJambiJawa TimurJawa TengahKalimantan SelatanKalimantan BaratKalimantan TimurKalimantan TengahKepulauan Bangka BelitungKalimantan UtaraLampungKepulauan RiauMaluku UtaraMalukuNusa Tenggara BaratNanggroe Aceh DarussalamPapua BaratRiauPapua TimurNusa Tenggara TimurPapuaSulawesi TengahSulawesi TenggaraSulawesi BaratSulawesi SelatanSumatera SelatanSumatera UtaraSulawesi UtaraSumatera Barat' or . = '
				                    	Please select state				                    BaliBantenBengkuluDaerah Istimewa YogyakartaDKI JakartaGorontaloJawa BaratJambiJawa TimurJawa TengahKalimantan SelatanKalimantan BaratKalimantan TimurKalimantan TengahKepulauan Bangka BelitungKalimantan UtaraLampungKepulauan RiauMaluku UtaraMalukuNusa Tenggara BaratNanggroe Aceh DarussalamPapua BaratRiauPapua TimurNusa Tenggara TimurPapuaSulawesi TengahSulawesi TenggaraSulawesi BaratSulawesi SelatanSumatera SelatanSumatera UtaraSulawesi UtaraSumatera Barat')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>province</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>state</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cascading</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                    	Please select state				                    BaliBantenBengkuluDaerah Istimewa YogyakartaDKI JakartaGorontaloJawa BaratJambiJawa TimurJawa TengahKalimantan SelatanKalimantan BaratKalimantan TimurKalimantan TengahKepulauan Bangka BelitungKalimantan UtaraLampungKepulauan RiauMaluku UtaraMalukuNusa Tenggara BaratNanggroe Aceh DarussalamPapua BaratRiauPapua TimurNusa Tenggara TimurPapuaSulawesi TengahSulawesi TenggaraSulawesi BaratSulawesi SelatanSumatera SelatanSumatera UtaraSulawesi UtaraSumatera Barat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='state']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='shipTo']/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dikirim ke'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
