<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPemesananLebihDari</name>
   <tag></tag>
   <elementGuidId>be146ffe-ab81-4ae5-a072-4ee65e190a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;activityFrom&quot;]/div/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'standard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>standard</value>
   </webElementProperties>
</WebElementEntity>
