<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableAccountNameLinkAja</name>
   <tag></tag>
   <elementGuidId>3939f772-d17f-43e5-8c26-27e50dda63ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tcashManagementTable']/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellspacing</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellpadding</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account NameLinkAja StatusMobile NumberLast Operation atoptionSiti_OnlineACTIVE08131401555028/11/2018 20:34:16 WIBviewjanejacobsACTIVE08128913833806/03/2019 13:42:26 WIBviewintanretnaACTIVE0811177554504/03/2019 09:54:12 WIBviewgrekerACTIVE08226930034528/11/2018 20:59:59 WIBviewagustinusdwiACTIVE08212805772207/03/2019 11:38:34 WIBviewalkhawarizmi1983ACTIVE081771983026/02/2019 09:03:26 WIBviewmndsyACTIVE08113890009004/03/2019 10:33:51 WIBviewandreasyulianto19_gmail_comACTIVE0811783780028/11/2018 21:58:42 WIBviewhuerixACTIVE08122969011128/11/2018 22:10:33 WIBviewtransportasiACTIVE08219984927428/11/2018 22:19:26 WIBview</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tcashManagementTable&quot;)/table[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='tcashManagementTable']/table</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number :'])[1]/following::table[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Name:'])[1]/following::table[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//table</value>
   </webElementXpaths>
</WebElementEntity>
