<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddLokasiKabRembang</name>
   <tag></tag>
   <elementGuidId>e2e11763-db8b-4fec-9fa4-dd71a6620350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'city' and (text() = 'Kab. PekalonganKab. BanjarnegaraKota TegalKab. TegalKab. PurbalinggaKab. SemarangKab. PemalangKab. GroboganKab. RembangKota SalatigaKab. BrebesKab. DemakKab. KendalKab. PatiKab. BanyumasKab. BatangKab. BloraKota SemarangKab. JeparaKab. KudusKota PekalonganKab. WonogiriKab. SukoharjoKab. SragenKab. KlatenKab. Karang AnyarKab. BoyolaliKota SurakartaKab. MagelangKab. TemanggungKab. PurworejoKab. WonosoboKab. KebumenKota MagelangKab. Cilacap' or . = 'Kab. PekalonganKab. BanjarnegaraKota TegalKab. TegalKab. PurbalinggaKab. SemarangKab. PemalangKab. GroboganKab. RembangKota SalatigaKab. BrebesKab. DemakKab. KendalKab. PatiKab. BanyumasKab. BatangKab. BloraKota SemarangKab. JeparaKab. KudusKota PekalonganKab. WonogiriKab. SukoharjoKab. SragenKab. KlatenKab. Karang AnyarKab. BoyolaliKota SurakartaKab. MagelangKab. TemanggungKab. PurworejoKab. WonosoboKab. KebumenKota MagelangKab. Cilacap')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-loxia-default mt8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cascading</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kab. PekalonganKab. BanjarnegaraKota TegalKab. TegalKab. PurbalinggaKab. SemarangKab. PemalangKab. GroboganKab. RembangKota SalatigaKab. BrebesKab. DemakKab. KendalKab. PatiKab. BanyumasKab. BatangKab. BloraKota SemarangKab. JeparaKab. KudusKota PekalonganKab. WonogiriKab. SukoharjoKab. SragenKab. KlatenKab. Karang AnyarKab. BoyolaliKota SurakartaKab. MagelangKab. TemanggungKab. PurworejoKab. WonosoboKab. KebumenKota MagelangKab. Cilacap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='city']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='location']/select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Fee Template'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loading......'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//select[2]</value>
   </webElementXpaths>
</WebElementEntity>
