<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Biaya_Pengiriman</name>
   <tag></tag>
   <elementGuidId>44e5e68e-8c8d-47a2-b63c-dd66b509902e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[1]/div[2]/div[3]/div[1]/div[1]/p[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[1]/div[2]/div[3]/div[1]/div[1]/p[2]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
